/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_library_InterfaceJNI */

#ifndef _Included_io_library_InterfaceJNI
#define _Included_io_library_InterfaceJNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     io_library_InterfaceJNI
	* Method:    getRoomInfo
	* Signature: ()Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_io_library_InterfaceJNI_getRoomInfo
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
