/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_core_InterfaceJNI */

#ifndef _Included_io_core_InterfaceJNI
#define _Included_io_core_InterfaceJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_core_InterfaceJNI
 * Method:    loadConfigurationFile
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_loadConfigurationFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    internalCalibration
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_internalCalibration
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    externalCalibration
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_externalCalibration
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    selectSVMclassifier
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_selectSVMclassifier
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    initializeSystem
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_initializeSystem
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jstring, jstring, jint, jstring, jint);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    startLocalizationEngine
 * Signature: (ZZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_startLocalizationEngine
  (JNIEnv *, jobject, jboolean, jboolean, jstring);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    platheaPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_platheaPlayer
  (JNIEnv *, jobject);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    platheaPlayerStart
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_platheaPlayerStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    platheaPlayerStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_platheaPlayerStop
  (JNIEnv *, jobject);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    getTrackedPeople
 * Signature: ()[Lio/core/InterfaceJNI/TrackedPerson;
 */
JNIEXPORT jobjectArray JNICALL Java_io_core_InterfaceJNI_getTrackedPeople
  (JNIEnv *, jobject);

/*
 * Class:     io_core_InterfaceJNI
 * Method:    getFrame
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_core_InterfaceJNI_getFrame
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
