/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_library_InterfaceJNI */

#ifndef _Included_io_library_InterfaceJNI
#define _Included_io_library_InterfaceJNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     io_library_InterfaceJNI
	* Method:    loadConfigurationFile
	* Signature: (Ljava/lang/String;)I
	*/
	JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_loadConfigurationFile
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     io_library_InterfaceJNI
	* Method:    internalCalibration
	* Signature: (Ljava/lang/String;I)I
	*/
	JNIEXPORT jint JNICALL Java_io_library_InterfaceJNI_internalCalibration
	(JNIEnv *, jobject, jstring, jint);

	/*
	* Class:     io_library_InterfaceJNI
	* Method:    loadExternalCalibrationData
	* Signature: (Ljava/lang/String;)I
	*/
	JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_loadExternalCalibrationData
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     io_library_InterfaceJNI
	* Method:    selectSVMclassifier
	* Signature: (Ljava/lang/String;)I
	*/
	JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_selectSVMclassifier
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     io_library_InterfaceJNI
	* Method:    initializeSystem
	* Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;ILjava/lang/String;I)I
	*/
	JNIEXPORT jint JNICALL Java_io_library_InterfaceJNI_initializeSystem
	(JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jstring, jstring, jint, jstring, jint);

	/*
	* Class:     io_library_InterfaceJNI
	* Method:    startLocalizationEngine
	* Signature: (ZZLjava/lang/String;)I
	*/
	JNIEXPORT jint JNICALL Java_io_library_InterfaceJNI_startLocalizationEngine
	(JNIEnv *, jobject, jboolean, jboolean, jstring);

	/*
	* Class:     io_library_InterfaceJNI
	* Method:    platheaRecorder_start
	* Signature: (Ljava/lang/String;)I
	*/
	JNIEXPORT jint JNICALL Java_io_library_InterfaceJNI_platheaRecorder_1start
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     io_library_InterfaceJNI
	* Method:    getPeopleInRoom
	* Signature: (I)Ljava/lang/String;
	*/
	JNIEXPORT jstring JNICALL Java_io_library_InterfaceJNI_getPeopleInRoom
	(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
