/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_core_InterfaceJNI */

#ifndef _Included_io_core_InterfaceJNI
#define _Included_io_core_InterfaceJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_core_InterfaceJNI
 * Method:    loadConfigurationFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_core_InterfaceJNI_loadConfigurationFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
