//{{NO_DEPENDENCIES}}
// File di inclusione generato con Microsoft Visual C++.
// Utilizzato da PLaTHEA.rc
//
#define IDOK2                           2
#define IDC_FIRST                       3
#define IDC_STARTLEFTINTERNAL           3
#define IDC_PREVIOUS                    4
#define IDC_STARTRIGHTINTERNAL          4
#define IDC_NEXT                        5
#define IDC_STARTSTEREO                 5
#define IDC_LAST                        6
#define ID_STATUS_BAR                   100
#define IDR_MENU                        101
#define ID_SNAPSHOT                     102
#define IDI_ICON                        103
#define IDR_ACCELERATOR1                104
#define IDD_INITIALIZE                  105
#define ID_DEBUG_INFO                   106
#define ID_LEFT_PANEL                   107
#define ID_RIGHT_PANEL                  108
#define IDD_SETTINGS                    110
#define IDD_EXTERNAL_CALIB              112
#define IDD_WORLDCOO                    113
#define IDD_ROOMDATA                    114
#define IDB_BITMAP1                     115
#define IDD_FACEDBASE                   116
#define IDD_SYNCTEST                    117
#define IDD_SYNCSTATS                   118
#define IDD_STEREO_CALIBRATION          119
#define IDR_RECTIFICATIONMENU           120
#define IDD_TESTDESIGNER                121
#define IDD_POSITIONTEST                122
#define IDD_STATISTICDIALOG             123
#define IDD_NEWPOSITIONTESTCHILD        126
#define IDD_COMPLETEOFFLINETEST         127
#define IDD_RECORDERDIALOG              128
#define IDD_MLDIALOG                    129
#define IDD_SVMDIALOG                   130
#define IDD_ACQUISITIONSTATISTIC        131
#define IDD_ALIGNIDIALOG                132
#define IDC_IPADDRESS1                  1001
#define IDC_IPADDRESS2                  1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_EDIT3                       1005
#define IDC_EDIT4                       1006
#define IDC_COMBO1                      1007
#define IDC_EDIT5                       1007
#define IDC_COMBO2                      1008
#define IDC_EDIT6                       1008
#define IDC_CHECK1                      1009
#define IDC_EDIT7                       1009
#define IDC_EDIT8                       1010
#define IDC_RIGHTCHECK                  1010
#define IDC_EDIT9                       1011
#define IDC_STEREOCHECK                 1011
#define IDC_EDIT10                      1012
#define IDC_EDIT11                      1013
#define IDC_EDIT12                      1014
#define IDC_EDIT13                      1015
#define IDC_EDIT14                      1016
#define IDC_EDIT15                      1017
#define IDC_EDIT16                      1018
#define IDC_EDIT17                      1019
#define IDC_EDIT18                      1020
#define IDC_EDIT19                      1021
#define IDC_EDIT20                      1022
#define IDC_EDIT21                      1023
#define IDC_EDIT22                      1024
#define IDC_EDIT23                      1025
#define IDC_EDIT24                      1026
#define IDC_EDIT25                      1027
#define IDC_EDIT26                      1028
#define IDC_EDIT27                      1029
#define IDC_LIST1                       1049
#define IDC_STATIC1                     1051
#define IDC_BUTTON1                     1052
#define IDC_BUTTON2                     1053
#define IDC_BUTTONDELETE                1054
#define IDC_BUTTON3                     1054
#define IDC_CHECK3                      1055
#define IDC_BUTTONADDPOINT              1055
#define IDC_BUTTON5                     1055
#define IDC_CHECK2                      1056
#define IDC_BUTTONNEWPATH               1056
#define IDC_BUTTON6                     1056
#define IDC_COMBO3                      1057
#define IDC_BUTTONLOADPATH              1057
#define IDC_COMBO4                      1058
#define IDC_SAVEPATH                    1058
#define IDC_SLIDER1                     1059
#define IDC_BUTTONDELETEPATH            1059
#define IDC_SLIDER2                     1060
#define IDC_BUTTONCOLOR                 1060
#define IDC_STATIC_LIGHT                1061
#define IDC_STATIC_THRESH               1062
#define IDC_STATIC_LEFT                 1063
#define IDC_STATIC_RIGHT                1064
#define IDC_RADIO1                      1065
#define IDC_RADIO2                      1066
#define IDC_RADIO3                      1067
#define IDC_STARTTEST                   1068
#define IDC_STOPTEST                    1069
#define IDC_STATIC_POS                  1070
#define IDC_DELETE                      1071
#define IDC_ANALYZE                     1072
#define IDC_COUPLEID                    1073
#define IDC_AVGFRAMERATE                1074
#define IDC_COUPLETRIGGERS              1074
#define IDC_AVGSTEREODIFFERENCE         1075
#define IDC_VARSTEREODIFFERENCE         1076
#define IDC_AVGDIFFSYNC                 1077
#define IDC_MAXDIFFERENCESYNC           1078
#define IDC_MINDIFFERENCESYNC           1079
#define IDC_UNSYNCTRANSITIONS           1080
#define IDC_DIRECTTRANSITIONS           1081
#define IDC_MAXSTEREODIFFERENCE         1082
#define IDC_MINSTEREODIFFERENCE         1083
#define IDC_SAVECALIBRATION             1084
#define IDC_LOADCALIBRATION             1085
#define IDC_LEFTINTERNALSTATIC          1086
#define IDC_RIGHTINTERNALSTATIC         1087
#define IDC_STEREOSTATIC                1088
#define IDC_STOPCURRENTCALIBRATION      1089
#define IDC_CHESSBOARDLEFT              1090
#define IDC_CHESSBOARDRIGHT             1091
#define IDC_TEXELSIDE                   1092
#define IDC_ROWNUMBER                   1093
#define IDC_COLNUMBER                   1094
#define IDC_LEFTCHECK                   1095
#define IDC_SINGLECALIBRATIONCHECK      1096
#define IDC_PATHBOX                     1097
#define IDC_RECTIFICATIONBYPARAMETERS   1097
#define IDC_BUTTONUP                    1098
#define IDC_BUTTONDOWN                  1099
#define IDC_EDITXCOORD                  1100
#define IDC_EDITYCOORD                  1101
#define IDC_COLORSTATIC                 1102
#define IDC_NUMBEROFSUBJECTSSPIN        1104
#define IDC_NUMBEROFSUBJECTSEDIT        1105
#define IDC_TESTLIST                    1106
#define IDC_PATHLIST                    1107
#define IDC_POSITIONTESTSTATIC          1108
#define IDC_USERMOUSELIST               1109
#define IDC_POSITIONTESTCLOSE           1110
#define IDC_STARTPOSITIONTEST           1111
#define IDC_BACKGROUNDSTATIC            1112
#define IDC_LEFTLITTLESTATIC            1113
#define IDC_RIGHTLITTLESTATIC           1114
#define IDC_FOREGROUNDCHECK             1115
#define IDC_PLANVIEWCHECK               1116
#define IDC_STOPPOSITIONTEST            1117
#define IDC_SAVETESTTOREPOSITORY        1118
#define IDC_BACKGROUNDMODELCHECK        1119
#define IDC_EDGEINTENSITYCHECK          1120
#define IDC_DISPARITYMAPCHECK           1121
#define IDC_STOREDTESTSLIST             1129
#define IDC_DELETESELECTEDTESTS         1131
#define IDC_EXPORTSTATS                 1132
#define IDC_TESTNAMEEDIT                1133
#define IDC_BUTTONNEWUSER               1134
#define IDC_BUTTONDELUSER               1135
#define IDC_BUTTONLOADUSER              1136
#define IDC_BUTTONSAVEUSER              1137
#define IDC_ACQUIREFACE                 1138
#define IDC_BUTTONPREVIOUSFACE          1139
#define IDC_BUTTONNEXTFACE              1140
#define IDC_BUTTONDELFACE               1141
#define IDC_PRESIZEDSTATIC              1142
#define IDC_CAPTURESTATIC               1143
#define IDC_CURRENTFACESTATIC           1144
#define IDC_PERSONEDIT                  1145
#define IDC_ACQUIREFACEFROMURI          1146
#define IDC_BROWSEPICDIRECTORY          1147
#define IDC_PICDIRECTORYEDIT            1148
#define IDC_FACEFILENAMEEDIT            1149
#define IDC_FACERECOGNITIONTEST         1150
#define IDC_EXECUTEDTESTSTATIC          1150
#define IDC_SHOWGROUNDTRUTHPATHS        1151
#define IDC_PERSONEDIT2                 1151
#define IDC_SHOWSWMEASUREMENTS          1152
#define IDC_PERSONEDIT3                 1152
#define IDC_HIGHLIGHTCORRESPONDENCES    1153
#define IDC_SHOWGRID                    1154
#define IDC_GRIDSTEPEDIT                1156
#define IDC_SELECTEDEXPERIMENTSCOMBO    1157
#define IDC_STATISTICLABEL              1158
#define IDC_STATISTICSSUBSETCOMBO       1159
#define IDC_ONLINETEST                  1161
#define IDC_OFFLINETEST                 1162
#define IDC_DATADIRECTORYEDIT           1163
#define IDC_DATADIRECTORYBUTTON         1164
#define IDC_POSITIONTESTTAB             1166
#define IDC_OFFLINETESTLIST             1168
#define IDC_OFFLINETESTDETAILS          1169
#define IDC_DELETEOFFLINETEST           1170
#define IDC_ADDITIONALDATADIRECTORYEDIT 1171
#define IDC_BUTTON4                     1172
#define IDC_TRACKEDSTATIC               1173
#define IDC_TRACKEDPICTURESTATIC        1174
#define IDC_DETECTEDOBJECTSTATIC        1175
#define IDC_CURRENTTRACKEDSTATIC        1176
#define IDC_COMBOLIST                   1177
#define IDC_PROGRESS1                   1178
#define IDC_LIST2                       1179
#define IDC_ACCURACYSTATIC              1180
#define IDC_LEFTFRAMESTATIC             1181
#define IDC_RIGHTFRAMESTATIC            1182
#define IDC_STEREOFRAMESTATIC           1183
#define ID_SISTEMA_INITIALIZESYSTEM     40001
#define ID_SYSTEM_ESCI                  40004
#define ID_SYSTEM_SYSTEMDETAILS         40007
#define ID_SYSTEM_STARTNEWCALIBRATION   40013
#define ID_SYSTEM_SAVECALIBRATIONDATA   40014
#define ID_SYSTEM_LOADCALIBRATIONDATA   40015
#define ID_LOCALIZATIONENGINE           40016
#define ID_LOCALIZATIONENGINE_STARTLOCALIZATIONENGINE 40017
#define ID_SYSTEM_STOPACQUISITION       40018
#define ID_LOCALIZATIONENGINE_STOPLOCALIZATIONENGINE 40019
#define ID_LOCALIZATIONENGINE_SETENGINEPARAMETERS 40020
#define ID_SHOWWINDOW_CURRENTBACKGROUND 40021
#define ID_SHOWWINDOW_FOREGROUND        40022
#define ID_SHOWWINDOW_EDGEACTIVITY      40023
#define ID_SHOWWINDOW_RAWDISPARITYMAP   40024
#define ID_SHOWWINDOW_CURRENTBACKGROUNDDISPARITY 40025
#define ID_SHOWWINDOW_DISPARITYMAPVSFOREGROUND 40026
#define ID_SHOWWINDOW_FILTEREDDISPARITYMAP 40027
#define ID_SHOWWINDOW_FILTEREDFOREGROUND 40028
#define ID_CALIBRATION_STARTEXTERNALCALIBRATION 40029
#define ID_CALIBRATION_LOADEXTERNALCALIBRATIONDATA 40030
#define ID_CALIBRATION_SAVEEXTERNALCALIBRATIONDATA 40031
#define ID_LOCALIZATIONENGINE_LOADSETTINGS 40039
#define ID_SHOWWINDOW_PLANVIEWOCCUPANCYMAP 40040
#define ID_SHOWWINDOW_PLANVIEWHEIGHTSMAP 40041
#define ID_CALIBRATION_EDITROOMSETTINGS 40042
#define ID_CALIBRATION_LOADROOMSETTINGS 40043
#define ID_CALIBRATION_SAVEROOMSETTINGS 40044
#define ID_LOCALIZATIONENGINE_ENDINITIALIZATIONPHASE 40045
#define ID_SYSTEM_LOADFACEDATABASE      40046
#define ID_SYSTEM_EDITFACEDATABASE      40047
#define ID_SYSTEM_SAVEFACEDATABASE      40048
#define ID_TEST_SYNCHRONIZATIONTEST     40049
#define ID_TEST_SHOWDEBUGCONSOLE        40050
#define ID_TEST_                        40051
#define ID_CALIBRATION_INTERNALCALIBRATIONPROCEDURE 40052
#define ID_RECTIFICATION_BOUGUETRECTIFICATION 40053
#define ID_RECTIFICATION_HARTLEYRECTIFICATION 40054
#define ID_SYSTEM_LOADCONFIGURATIONFILE 40055
#define ID_SYSTEM_SAVECONFIGURATIONFILE 40056
#define ID_SYSTEM_SAVECONFIGURATIONFILEAS 40057
#define ID_SYSTEM_SELECTHAARCASCADEXML  40058
#define ID_TEST_TESTDESIGNER            40059
#define ID_TEST_POSITIONTEST            40060
#define ID_TEST_STATISTICANALYZER       40061
#define ID_SYSTEM_SELECTFACEDATABASEDIRECTORY 40062
#define ID_TEST_STARTVIDEORECORDING     40063
#define ID_TEST_STOPVIDEORECORDINGANDSAVE 40064
#define ID_TEST_PLATHEARECORDER         40065
#define ID_TEST_SVMLEARNING             40066
#define ID_LOCALIZATIONENGINE_SELECTSVMCLASSIFIER 40067
#define ID_SYSTEM_HIDEVIDEOINPUT        40068
#define ID_SYSTEM_ACQ                   40069
#define ID_SYSTEM_ACQUISITIONSTATS      40070
#define ID_TEST_SAVETRACKSTOFILE        40071
#define ID_LOCALIZATIONENGINE_OPTICALFLOW 40072
#define ID_LOCALIZATIONENGINE_SVM       40073
#define ID_RECTIFICATION_RECTIFYBYPARAMETERS 40074
#define ID_SYSTEM_ALIGNRIGHTFRAME       40075

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40076
#define _APS_NEXT_CONTROL_VALUE         1186
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
